blank_issues_enabled true
contact_links
  - name 整合包官方频道
    url https://qun.qq.com/qqweb/qunpro/share?_wv=3&_wwv=128&appChannel=share&inviteCode=1W4ylq9&appChannel=share&businessType=9&from=246610&biz=ka
    about 寄生虫：血染黎明整合包的官方频道。
  - name 爱发电
    url https://afdian.net/@pipilan
    about 前往爱发电赞助皮皮懒，帮助他做更多好的作品。